MODEL:
  META_ARCHITECTURE: "Pirt"
  TEL: 3

  BACKBONE:
    NAME: "build_resnet_backbone"
    NORM: "BN"
    DEPTH: "50x"
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: True
    WITH_NL: False
    PRETRAIN: True
    PRETRAIN_PATH: "../models_zoo/resnet50_ibn_a-d9d0bb7b.pth"

  POSENET:
    NAME: "build_pose_hrnet"
    PRETRAIN: True
    PRETRAIN_PATH: '../models_zoo/pose_hrnet_w48_256x192.pth'
    PRETRAINED_LAYERS: ['*']
    STEM_INPLANES: 64
    FINAL_CONV_KERNEL: 1
    NUM_JOINTS: 17

    JOINTS_GROUPS: [
        [5, 7, 9, 6, 8, 10], [11, 13, 15, 12, 14, 16], [0, 1, 2, 3, 4, 5],
    ]
    WIDTH: '48x'

  HEADS:
    NAME: "AGGHead"
    NORM: "BN"
    WITH_BNNECK: True
    POOL_LAYER: "avgpool"
    NECK_FEAT: "before"
    CLS_LAYER: "linear"

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss", )

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.


INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True
  PADDING: 10
  CJ:
    ENABLED: False

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPT: "Adam"
  MAX_ITER: 60
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "WarmupCosineAnnealingLR"
  DELAY_ITERS: 30
  ETA_MIN_LR: 0.000001

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  CHECKPOINT_PERIOD: 30

TEST:
  EVALUATOR: "PirtEvaluator"
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
  METRIC: "cosine"

CUDNN_BENCHMARK: True

DATASETS:
  NAMES: ("OccludedDuke", )
  TESTS: ("OccludedDuke", )

OUTPUT_DIR: "logs/test"
